Repository framgia/sph-lms, pull requests merged in 2023-07, with the labels that each got.

#158 LMS-689 Fix build error
  client/src/sections/learning-paths/settingsSection/EditSettingsButton.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Elyric is Reviewing, Approved by Jules

#160 LMS-690 [Course Detail Page] [Settings Tab] Description Not Updating
  api/app_sph_lms/api/serializer/course_serializer.py
Labels: For Review, Approved by Elyric, Approved by Amber

#161 [LMS-691] [BUGFIX] [Course & Learning Path] [Settings Tab] Update Description display and Delete Confirmation Should use Dynamic name
  client/src/sections/courses/SettingsSection/index.tsx
  client/src/sections/courses/create/InitialSection.tsx
  client/src/sections/learning-paths/create/InitialSection.tsx
  client/src/shared/components/ReactForm/RFTextField/index.tsx
Labels: For Review, Approved by Elyric

#162 [LMS-692] [BUGFIX] [Learning Path Detail Page] Display courses by order & hide drag icon on non-edit mode
  api/app_sph_lms/api/serializer/learning_path_serializer.py
  api/app_sph_lms/api/view/learning_path_view.py
  client/src/sections/learning-paths/create/CourseItem.tsx
  client/src/shared/components/Collapse/Collapse.tsx
Labels: Approved by Franz, Franz is Reviewing, Approved by Elyric

#159 [LMS-693]-[Bugfix] Make Button Style Uniform
  client/src/pages/trainer/courses/index.tsx
  client/src/sections/courses/LearningSection/index.tsx
  client/src/sections/learning-paths/LearnersSection/index.tsx
  client/src/shared/components/Button/EditModeButtons.tsx
Labels: For Review, Approved by Mel, Approved by Jules

#163 [LMS-694] [BUGFIX] [Course & Learning Path] [Settings Tab] Settings Tab details is not showing on visiting another Course/LP coming from another Course/LP
  client/src/pages/trainer/courses/[id]/index.tsx
  client/src/pages/trainer/learning-paths/[id]/index.tsx
  client/src/sections/courses/SettingsSection/index.tsx
  client/src/sections/learning-paths/settingsSection/index.tsx
Labels: For Review, Approved by Mel, Approved by Amber

#164 [LMS-695][MARKUP] [Course Page] change loading display from Loading..…
  client/src/pages/trainer/courses/index.tsx
  client/src/sections/learning-paths/index.tsx
Labels: For Review, Approved by Mel, Approved by Jules

#165 [LMS-701][MARKUP] Refactor Learning Path Design
  client/src/sections/learning-paths/ContentSection/index.tsx
  client/src/shared/components/Card/LearningPathCourseCard/index.tsx
Labels: For Review, Franz is Reviewing, Mel is Reviewing

#167 [LMS-702][API/INTEGRATION] Update API response and integration
  client/src/sections/learning-paths/ContentSection/index.tsx
Labels: For Review, Approved by Mel, Approved by Elyric

#166 LMS-704 [API/Integration] Progress Percentage Display and Sort for En…
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/api/serializer/learning_path_serializer.py
  api/app_sph_lms/api/view/course_view.py
  api/app_sph_lms/api/view/learning_path_view.py
  api/app_sph_lms/api/view/trainee_view.py
  api/app_sph_lms/api/view/trainer_view.py
  api/app_sph_lms/migrations/0001_initial.py
  api/app_sph_lms/models.py
  api/app_sph_lms/utils/pagination.py
  api/app_sph_lms/utils/progress_calculator.py
  api/app_sph_lms/utils/sorting.py
  client/src/pages/trainer/courses/index.tsx
  client/src/sections/courses/LearningSection/index.tsx
  client/src/sections/courses/create/Lessons.tsx
  client/src/sections/dashboard/TraineesSection.tsx
  client/src/sections/dashboard/trainee/CoursesSection.tsx
  client/src/sections/learning-paths/LearnersSection/index.tsx
  client/src/sections/learning-paths/create/Courses.tsx
  client/src/sections/learning-paths/index.tsx
  client/src/services/traineeAPI.ts
  client/src/shared/components/Dropdown/SortDropdown/DropDownOptions.tsx
  client/src/shared/components/Dropdown/SortDropdown/SortDropdown.tsx
  client/src/shared/components/StudentActivity/index.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Mel, Approved by Amber

#171 LMS-708 [MARKUP] Fix State for Stepper and Create of Course and learn…
  client/src/pages/trainer/courses/index.tsx
  client/src/pages/trainer/learning-paths/index.tsx
  client/src/shared/components/Stepper/index.tsx
Labels: For Review, Approved by Mel, Approved by Amber

#170 [LMS-707][MARKUP] Course & Learning Path List Page
  client/src/pages/trainer/courses/index.tsx
  client/src/pages/trainer/learning-paths/index.tsx
Labels: For Review, Approved by Rene, Approved by Mel

#172 [LMS-706] [Course & Learning Path] CREATE error message
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/migrations/0003_alter_course_name.py
  api/app_sph_lms/models.py
  client/src/pages/trainer/courses/create/index.tsx
  client/src/pages/trainer/learning-paths/create/index.tsx
Labels: For Review, Approved by Rene, Approved by Mel

#174 [LMS-715] [BUGFIX] Fix build, button, & drag icon on learning path create
  client/src/pages/trainer/learning-paths/index.tsx
  client/src/sections/learning-paths/ContentSection/index.tsx
  client/src/sections/learning-paths/create/CourseItem.tsx
  client/src/shared/components/Modal/AddLearnerModal.tsx
Labels: Approved by Mel, Approved by Amber

#175 [DevServer] Authentication Issues
  api/app_sph_lms/api/view/auth_view.py
Labels: Approved by Mel, Approved by Amber

#176 [LMS-710][MARKUP] Course View (overview)
  client/package-lock.json
  client/src/pages/trainee/course/[id]/index.tsx
Labels: For Review, Mel is Reviewing, Approved by Amber

#173 [LMS-712] [API/Integration] Course View (overview)
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/api/view/course_view.py
  client/src/pages/trainee/course/[id]/index.tsx
  client/src/sections/dashboard/trainee/CoursesSection.tsx
  client/src/services/traineeAPI.ts
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Mel, Approved by Jules

#178 [LMS-711][MARKUP] Create Training Page
  client/src/pages/trainee/course/[id]/training/index.tsx
  client/src/sections/courses/ContentSection.tsx
  client/src/shared/components/SidebarContent/index.tsx
Labels: For Review, Approved by Rene, Approved by Mel

#177 LMS-713 [API/INTEGRATION] Training Page
  api/app_sph_lms/api/serializer/completed_lesson_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/completed_lesson_views.py
  client/src/pages/trainee/course/[id]/training/index.tsx
  client/src/services/traineeAPI.ts
  client/src/shared/components/SidebarContent/SideBar.tsx
  client/src/shared/components/SidebarContent/index.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Franz is Reviewing, Approved by Mel

#179 LMS-714 [MARKUP/INTEGRATION] Trainee Learning Path Page
  client/src/pages/trainee/course/[id]/index.tsx
  client/src/pages/trainee/learning-path/[id]/index.tsx
  client/src/sections/learning-paths/ContentSection/index.tsx
  client/src/services/traineeAPI.ts
  client/src/shared/components/Card/LearningPathCard/index.tsx
Labels: For Review, Approved by Franz, Approved by Mel

#180 LMS-703 [DevServer] Authentication issues V2
  api/app_sph_lms/apps.py
  api/app_sph_lms/signals.py
Labels: For Review, Franz is Reviewing, Approved by Mel

#181 LMS-716 Fix Index Page Redirection
  api/app_sph_lms/signals.py
  client/src/pages/index.tsx
Labels: For Review, Franz is Reviewing, Approved by Mel

#182 LMS-717 Bugfix on Edit Course
  client/src/sections/courses/SettingsSection/EditSettingsButton.tsx
Labels: For Review, Franz is Reviewing, Approved by Mel
