Repository framgia/sph-lms, pull requests merged in 2023-04, with the labels that each got.

#66 [BE][API] User List
  api/Pipfile
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/views.py
  api/app_sph_lms/fixtures/seeder.json
  api/app_sph_lms/fixtures/user.json
  api/app_sph_lms/migrations/0001_initial.py
  api/app_sph_lms/models.py
Labels: For Review, Approved by Marielle, Approved by Miko

#67 [BE][API] User List Sorting Column
  api/app_sph_lms/api/serializers.py
Labels: For Review, Approved by Marielle, Approved by Miko

#70 [BUGFIX][BE][API] User Create Retrieve API
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/views.py
Labels: For Review, Approved by Marielle, Approved by Miko

#73 [LMS-362][BUG FIX] Sign up button
  client/src/pages/demo/components/index.tsx
  client/src/pages/trainer/course/create.tsx
  client/src/pages/trainer/course/detail/[id].tsx
  client/src/sections/landing-page/NavbarSection.tsx
  client/src/shared/layouts/CourseSettingTab/index.tsx
Labels: For Review, Approved by Marielle, Approved by Rene

#69 [LMS-352][BE][Integration]- User List
  client/src/pages/users/[company_id]/list/index.tsx
  client/src/shared/hooks/useShowUserList.ts
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Marielle, Approved by Rene

#74 [LMS-366][Refactor][FE] Class List Add Button
  client/package-lock.json
  client/package.json
  client/src/pages/auth/sign-in/index.tsx
  client/src/pages/classes/[company_id]/list/index.tsx
  client/src/pages/demo/components/index.tsx
  client/src/sections/classes/AddClassModal.tsx
  client/src/shared/components/Button/index.tsx
  client/src/shared/components/ReactForm/RFInputField/index.tsx
  client/src/shared/hooks/useAuthSignIn.ts
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Marielle, Approved by Miko

#68 [LMS-360][Integration] User List Sorting Column
  client/src/pages/demo/components/data.json
  client/src/pages/demo/components/index.tsx
  client/src/pages/demo/layouts/LearnersTab.tsx
  client/src/pages/trainer/course/[id]/enrollUser.tsx
  client/src/pages/trainer/courses/list/index.tsx
  client/src/pages/users/[company_id]/list/index.tsx
  client/src/shared/components/Table/index.tsx
  client/src/shared/hooks/useShowUserList.ts
Labels: For Review, Approved by Marielle, Approved by Miko

#76 LMS-367-[BE][Seeder & API] Class List
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/views.py
  api/app_sph_lms/fixtures/user.json
  package-lock.json
Labels: For Review, Approved by Marielle, Approved by Rene

#75 [LMS-365][FE] Class List, Search, Pagination
  client/package-lock.json
  client/src/pages/auth/sign-in/index.tsx
  client/src/pages/classes/[company_id]/list/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/hooks/useAuthSignIn.ts
  client/src/shared/hooks/useShowClassList.ts
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Marielle, Rene is reviewing

#72 [LMS-363][BUG FIX] Course List Filter
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/views.py
Labels: For Review, Approved by Marielle, Approved by Rene

#77 [LMS-369][INTEGRATION] Class List Sort By Column
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/views.py
  api/app_sph_lms/fixtures/seeder.json
  api/app_sph_lms/fixtures/user.json
  api/app_sph_lms/migrations/0001_initial.py
  api/app_sph_lms/migrations/0002_alter_trainee_company_alter_trainee_trainee_and_more.py
  api/app_sph_lms/models.py
  client/src/pages/classes/[company_id]/list/index.tsx
  client/src/pages/users/[company_id]/list/index.tsx
  client/src/shared/hooks/useShowClassList.ts
  client/src/shared/hooks/useShowUserList.ts
Labels: For Review, Approved by Marielle, Miko is reviewing

#80 [LMS-376][BUGFIX] Authentication Middleware
  client/src/shared/hooks/useAuthMiddleware.ts
  client/src/shared/hooks/useAuthSignIn.ts
  client/src/shared/hooks/useSignOut.ts
  client/src/shared/utils/axios.ts
  client/src/shared/utils/index.ts
  client/src/shared/utils/localStorage.ts
Labels: For Review, Approved by Marielle, Miko is reviewing

#79 [LMS-368][Integration]Class List, Pagination
  api/app_sph_lms/api/views.py
  client/src/pages/classes/[company_id]/list/index.tsx
  client/src/shared/hooks/useShowClassList.ts
Labels: For Review, Approved by Marielle, Approved by Rene

#81 [LMS-372][Bugfix][FE] Sign In Page
  client/public/sun-asterisk-logo.png
  client/src/pages/auth/sign-in/index.tsx
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Logo/index.tsx
Labels: For Review, Approved by Marielle, Approved by Miko

#83 [LMS-373][Bugfix][Integration] Create Course Page
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/views.py
  client/package-lock.json
  client/package.json
  client/src/pages/trainer/course/create.tsx
  client/src/shared/components/ReactForm/RFTextField/index.tsx
  client/src/shared/hooks/useCreateCourse.ts
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Marielle, Approved by Miko

#84 [LMS-374][INTEGRATION] Enroll User Page
  client/src/pages/trainer/course/[id]/enrollUser.tsx
  client/src/shared/hooks/useEnrollUser.ts
  client/src/shared/hooks/useShowPerPage.ts
  client/src/shared/utils/axios.ts
Labels: For Review, Approved by Marielle, Approved by Rene
