Repository framgia/sph-lms, pull requests merged in 2023-05, with the labels that each got.

#86 [LMS-332][FE/BE] [Enroll User] Pagination
  client/src/pages/trainer/course/[id]/enrollUser.tsx
  client/src/shared/hooks/useEnrollUser.ts
Labels: Approved by Rene, Approved by Zion, Approved by Mel

#87 [LMS-382][FE] Add Material Modal
  client/.eslintrc.json
  client/src/pages/element/material/index.tsx
  client/src/sections/material/AddMaterialModal.tsx
  client/src/sections/material/MaterialForm.tsx
  client/src/shared/components/Collapse/DivCollapse.tsx
  client/src/shared/components/Modal/Modal.tsx
  client/src/shared/components/ReactForm/RFInputField/index.tsx
  client/src/shared/components/TabButton/index.tsx
  client/src/shared/utils/interface.ts
Labels: Approved by Zion, Approved by Mel, Approved by Vali

#89 LMS-378 - [FE] Material List, Search, Buttons
  client/src/pages/element/material/index.tsx
  client/src/sections/users/usersUpdateDelete.tsx
  client/src/shared/components/Dropdown/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/components/Select/index.tsx
  client/src/shared/components/Table/HeaderTitle.tsx
  client/src/shared/components/Table/Icon.tsx
  client/src/shared/components/Table/ListItem.tsx
  client/src/shared/components/Table/index.tsx
  client/src/shared/icons/EditIcon.tsx
  client/src/shared/icons/FileIcon.tsx
  client/src/shared/icons/FolderIcon.tsx
  client/src/shared/icons/LinkIcon.tsx
  client/src/shared/icons/TrashIcon.tsx
  client/src/shared/icons/VideoIcon.tsx
  client/src/shared/utils/navBarList.ts
Labels: For Review, Approved by Rene, Approved by Mel

#93 LMS-614 - [Markup] Update Navbar for the trainers page
  client/public/default-icon.webp
  client/src/pages/_app.tsx
  client/src/pages/classes/[company_id]/list/index.tsx
  client/src/pages/demo/components/index.tsx
  client/src/pages/demo/layouts/LearnersTab.tsx
  client/src/pages/demo/layouts/navbar.tsx
  client/src/pages/element/material/index.tsx
  client/src/pages/home/index.tsx
  client/src/pages/trainer/course/[id]/enrollUser.tsx
  client/src/pages/trainer/course/create.tsx
  client/src/pages/trainer/course/detail/[id].tsx
  client/src/pages/users/[company_id]/list/index.tsx
  client/src/shared/components/Avatar/index.tsx
  client/src/shared/components/Dropdown/index.tsx
  client/src/shared/components/Navbar/Logo.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/icons/NotificationIcon.tsx
  client/src/shared/icons/SunBear.tsx
  client/src/shared/utils/navBarList.ts
  client/tailwind.config.js
Labels: For Review, Approved by Mel, EJ is reviewing

#95 LMS-613 - State management setting up
  client/app/hooks.ts
  client/app/store.ts
  client/features/counter/counterSlice.ts
  client/package-lock.json
  client/package.json
  client/src/pages/_app.tsx
  client/src/pages/demo/components/index.tsx
Labels: For Review, Approved by Rene, Approved by Elyric

#96 [LMS-602][Markup][Content tab]
  client/src/pages/trainer/courses/[id]/enrollUser.tsx
  client/src/pages/trainer/courses/[id]/index.tsx
  client/src/pages/trainer/courses/create.tsx
  client/src/pages/trainer/courses/detail/[id].tsx
  client/src/pages/trainer/courseslist/list/index.tsx
  client/src/sections/courses/ContentSection.tsx
  client/src/shared/components/Breadcrumbs/index.tsx
  client/src/shared/components/SidebarContent/SideBar.tsx
  client/src/shared/components/SidebarContent/index.tsx
  client/src/shared/components/Tabs/Tab.tsx
  client/src/shared/components/Tabs/index.tsx
  client/src/shared/layouts/Container/index.tsx
  client/src/shared/utils/interface.ts
  client/tailwind.config.js
Labels: Approved by Mel, Approved by Vali

#97 Feature/lms 615
  .pre-commit-config.yaml
  client/.eslintignore
  client/.eslintrc.json
  client/.prettierrc
Labels: For Review, Approved by Rene, Approved by Mel

#94 LMS-596 - [Markup] Trainer can view a list of courses
  client/next.config.js
  client/src/pages/trainer/courses/index.tsx
  client/src/shared/components/Button/index.tsx
  client/src/shared/components/Card/CourseCard/index.tsx
  client/src/shared/components/Pagination/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/icons/ArrowIcon.tsx
  client/src/shared/icons/DoubleArrowIcon.tsx
  client/src/shared/icons/NextIcon.tsx
  client/src/shared/icons/PreviousIcon.tsx
  client/src/shared/utils/interface.ts
  client/src/shared/utils/navBarList.ts
  client/tailwind.config.js
Labels: Approved by Mel, Approved by Vali

#101 LMS-599 - [Markup] Trainer can add new courses
  client/.eslintrc.json
  client/app/store.ts
  client/features/course/courseSlice.ts
  client/features/course/lessonModalsSlice.ts
  client/features/stepper/stepperSlice.ts
  client/package-lock.json
  client/package.json
  client/src/pages/trainer/courses/create.tsx
  client/src/pages/trainer/courses/create/index.tsx
  client/src/pages/trainer/courses/detail/[id].tsx
  client/src/pages/trainer/courses/index.tsx
  client/src/pages/trainer/courseslist/list/index.tsx
  client/src/sections/courses/create/AddLessonSection.tsx
  client/src/sections/courses/create/InitialSection.tsx
  client/src/sections/courses/create/LessonItem.tsx
  client/src/sections/courses/create/LessonModal.tsx
  client/src/sections/courses/create/PreviewSection.tsx
  client/src/shared/components/Breadcrumbs/index.tsx
  client/src/shared/components/Button/index.tsx
  client/src/shared/components/Modal/DeleteModal.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/components/ProgressBar/index.tsx
  client/src/shared/components/ReactForm/RFInputField/index.tsx
  client/src/shared/components/ReactForm/RFTextField/index.tsx
  client/src/shared/components/Stepper/Step.tsx
  client/src/shared/components/Stepper/index.tsx
  client/src/shared/icons/EditIcon.tsx
  client/src/shared/icons/ExclamationPointIcon.tsx
  client/src/shared/icons/FourDotsIcon.tsx
  client/src/shared/icons/PlusIcon.tsx
  client/src/shared/icons/TrashIcon.tsx
  client/src/shared/icons/XmarkIcon.tsx
  client/src/shared/layouts/Container/index.tsx
  client/src/shared/utils/helpers.ts
  client/src/shared/utils/interface.ts
  client/src/shared/utils/validationSchemas.ts
  client/styles/globals.css
  client/tailwind.config.js
Labels: For Review, Approved by Rene, Approved by Mel

#103 LMS-607 - [Markup] [Learners tab] Trainer can visit learners tab in c…
  .vscode/settings.json
  client/src/pages/trainer/courses/[id]/index.tsx
  client/src/sections/courses/LearningSection/AddLearnerModal.tsx
  client/src/sections/courses/LearningSection/index.tsx
  client/src/shared/components/Dropdown/SortDropdown/SortDropdown.tsx
  client/src/shared/components/Modal/Modal.tsx
  client/src/shared/components/ProgressPercentage/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/icons/CloseIcon.tsx
  client/src/shared/icons/FilterIcon.tsx
  client/src/shared/icons/ShowIcon.tsx
  client/src/shared/icons/UnShowIcon.tsx
  client/src/shared/utils/interface.ts
  client/tailwind.config.js
Labels: Rene is reviewing, Approved by Mel

#104 LMS-616 Pre-commit errors hotfix
  .pre-commit-config.yaml
  client/.eslintrc.json
Labels: For Review, Approved by Rene, Approved by Elyric

#106 LMS-608 & LMS-611 - [Markup] [Settings tab] Trainer can visit learners tab in course detail page & Drag and drop lesson component
  client/app/store.ts
  client/features/course/courseSlice.ts
  client/features/tab/tabSlice.ts
  client/package-lock.json
  client/package.json
  client/src/pages/trainer/courses/[id]/index.tsx
  client/src/sections/courses/SettingsSection/EditSettingsButton.tsx
  client/src/sections/courses/SettingsSection/index.tsx
  client/src/sections/courses/create/AddLessonSection.tsx
  client/src/sections/courses/create/InitialSection.tsx
  client/src/sections/courses/create/LessonItem.tsx
  client/src/sections/courses/create/Lessons.tsx
  client/src/shared/components/Collapse/Collapse.tsx
  client/src/shared/components/Collapse/DivCollapse.tsx
  client/src/shared/components/NavLink/index.tsx
  client/src/shared/components/Tabs/index.tsx
  client/src/shared/hooks/useConfirmBeforeLeave.ts
  client/src/shared/hooks/useStrictDroppable.ts
  client/src/shared/icons/EllipsesHorizontalIcon.tsx
  client/src/shared/icons/FilterIcon.tsx
  client/src/shared/icons/ShowIcon.tsx
  client/src/shared/icons/UnShowIcon.tsx
  client/src/shared/utils/interface.ts
  client/src/shared/utils/validationSchemas.ts
  client/tailwind.config.js
Labels: For Review, Rene is reviewing, Approved by Mel

#100 [LMS-604][API/ Integration] [Learners tab] List of associated learners in course detail page
  api/app_sph_lms/admin.py
  api/app_sph_lms/api/serializer/class_serializer.py
  api/app_sph_lms/api/serializer/company_serializer.py
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/api/serializer/trainee_serializer.py
  api/app_sph_lms/api/serializer/trainer_serializer.py
  api/app_sph_lms/api/serializer/user_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/trainee_view.py
  api/app_sph_lms/api/view/user_view.py
  api/app_sph_lms/migrations/0003_alter_lesson_course_coursetrainee.py
  api/app_sph_lms/models.py
  client/app/store.ts
  client/services/traineeAPI.ts
  client/src/sections/courses/ContentSection.tsx
  client/src/sections/courses/LearningSection/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/utils/interface.ts
Labels: Approved by Mel, Approved by Vali, Approved by Elyric

#108 LMS-597 [API/ INTEGRATION] Trainer can view a list of courses
  api/app/settings.py
  api/app_sph_lms/api/view/course_view.py
  api/app_sph_lms/fixtures/user.json
  client/app/store.ts
  client/services/courseAPI.ts
  client/src/pages/trainer/courses/index.tsx
  client/src/shared/components/Card/CourseCard/index.tsx
  client/src/shared/components/Pagination/index.tsx
  client/src/shared/utils/interface.ts
Labels: Approved by Mel, Approved by Amber

#105 [LMS-598] [API/Integration] Trainer can search courses
  api/app_sph_lms/api/view/course_view.py
  client/app/store.ts
  client/services/courseAPI.ts
  client/src/pages/trainer/courses/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
Labels: For Review, Approved by Mel, Approved by Jules

#107 LMS-607-[Hotfix][Markup][Learners tab] Trainer can visit learners tab…
  client/.eslintrc.json
  client/.prettierrc
  client/src/shared/components/Dropdown/SortDropdown/SortDropdown.tsx
  client/src/shared/icons/FilterIcon.tsx
Labels: Approved by Mel, Approved by Amber

#98 [LMS-609][API/Integration] [Learners tab] List all learners and Add n…
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/trainee_view.py
  api/app_sph_lms/forms.py
  api/app_sph_lms/migrations/0003_alter_lesson_course_coursetrainee.py
  client/app/store.ts
  client/features/course/learnerSlice.ts
  client/services/traineeAPI.ts
  client/src/sections/courses/LearningSection/AddLearnerModal.tsx
  client/src/sections/courses/LearningSection/index.tsx
  client/src/shared/components/Button/index.tsx
Labels: Approved by Mel, Approved by Vali

#110 [LMS-620] [Markup] Trainer can view a list of learning paths
  client/src/pages/trainer/learning-paths/index.tsx
  client/src/shared/components/Card/LearningPathCard/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/components/Tabs/index.tsx
  client/src/shared/utils/interface.ts
  client/src/shared/utils/navBarList.ts
  client/tailwind.config.js
Labels: For Review, Approved by Mel, Approved by Jules

#112 Deployment Hotfixes
  client/src/pages/demo/components/data.json
  client/src/pages/demo/components/index.tsx
  client/src/pages/demo/layouts/Container.tsx
  client/src/pages/demo/layouts/LearnersTab.tsx
  client/src/pages/demo/layouts/Learning.tsx
  client/src/pages/demo/layouts/SidebarLayout.tsx
  client/src/pages/demo/layouts/navbar.tsx
  client/src/pages/demo/layouts/sidebar.tsx
  client/src/pages/demo/layouts/tabs.tsx
  client/src/sections/courses/ContentSection.tsx
  client/src/sections/courses/list/right-side-container.tsx
  client/src/sections/courses/list/view-as.tsx
  client/src/shared/cards/GridCard.tsx
  client/src/shared/cards/ListCard.tsx
  client/src/shared/components/Pagination/index.tsx
  client/src/shared/layouts/CourseSettingTab/index.tsx
  client/src/shared/layouts/CourseSettingsSideBar/index.tsx
  client/src/shared/layouts/LayoutLearning/LayoutLearning.tsx
  client/src/shared/layouts/LayoutLearning/Sidebar.tsx
  client/src/shared/layouts/SideBar/index.tsx
  client/src/shared/layouts/tabs.tsx
Labels: For Review, Approved by Mel, Approved by Vali
