Repository framgia/sph-lms, pull requests merged in 2023-06, with the labels that each got.

#99 [LMS-600][API/ Integration] Trainer can add new courses
  api/app_sph_lms/api/serializer/category_serializer.py
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/api/view/category_view.py
  api/app_sph_lms/api/view/course_view.py
  api/app_sph_lms/migrations/0002_lesson.py
  api/app_sph_lms/migrations/0002_remove_course_status_course_category_and_more.py
  api/app_sph_lms/migrations/0003_alter_lesson_course_coursetrainee.py
  api/app_sph_lms/migrations/0003_alter_lesson_link.py
  api/app_sph_lms/migrations/0004_alter_lesson_order.py
  api/app_sph_lms/migrations/0005_alter_lesson_order.py
  api/app_sph_lms/models.py
  client/app/store.ts
  client/features/course/courseSlice.ts
  client/package-lock.json
  client/services/categoryAPI.ts
  client/services/courseAPI.ts
  client/src/pages/trainer/courses/create/index.tsx
  client/src/sections/courses/create/InitialSection.tsx
  client/src/shared/components/Card/CourseCard/index.tsx
  client/src/shared/utils/interface.ts
  client/src/shared/utils/validationSchemas.ts
Labels: Approved by Mel, Approved by Vali

#111 [LMS-625][Markup][Learners tab] Add new learner modal
  client/src/pages/trainer/learning-paths/[id]/index.tsx
  client/src/sections/learning-paths/LearnersSection/index.tsx
  client/src/shared/components/Button/index.tsx
  client/src/shared/components/Modal/AddLearnerModal.tsx
  client/src/shared/components/Modal/Modal.tsx
Labels: For Review, Approved by Rene, Mel is Reviewing, Approved by Jules

#114 [LMS-634] [Markup] [Content Tab] Trainer can visit content tab in learning path detail page
  client/src/pages/trainer/learning-paths/[id]/index.tsx
  client/src/sections/learning-paths/ContentSection/index.tsx
  client/src/sections/learning-paths/create/PreviewSection.tsx
  client/src/shared/components/Card/CourseCard/index.tsx
  client/src/shared/components/Card/LearningPathCourseCard/index.tsx
Labels: For Review, Approved by Mel, Approved by Vali, Mel is Reviewing, Approved by Elyric

#119 LMS-610 [API/ Integration] [Learners tab] Sorting learners
  api/app_sph_lms/api/serializer/course_serializer.py
  client/features/course/learnerSlice.ts
  client/services/traineeAPI.ts
  client/src/sections/courses/LearningSection/index.tsx
  client/src/shared/components/Dropdown/index.tsx
Labels: For Review, Approved by Rene, Approved by Mel

#115 [LMS-605] & [LMS-612] [API/ Integration] Settings tab in course detai…
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/api/view/course_view.py
  api/app_sph_lms/models.py
  client/services/courseAPI.ts
  client/src/sections/courses/SettingsSection/EditSettingsButton.tsx
  client/src/sections/courses/SettingsSection/index.tsx
Labels: For Review, Approved by Rene, Approved by Mel

#125 [LMS-647] Navbar notification icon & profile picture fix
  client/src/shared/components/Avatar/index.tsx
  client/src/shared/components/Navbar/index.tsx
Labels: For Review, Approved by Rene, Approved by Mel

#118 [API/ Integration] [Learners tab] List learners in learners tab and i…
  api/app_sph_lms/admin.py
  api/app_sph_lms/api/serializer/learning_path_serializer.py
  api/app_sph_lms/api/serializer/user_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/trainee_view.py
  api/app_sph_lms/fixtures/seeder.json
  api/app_sph_lms/migrations/0001_initial.py
  api/app_sph_lms/migrations/0002_remove_course_status_course_category_and_more.py
  api/app_sph_lms/migrations/0003_alter_lesson_link.py
  api/app_sph_lms/migrations/0004_alter_lesson_order.py
  api/app_sph_lms/migrations/0005_alter_lesson_order.py
  api/app_sph_lms/migrations/0006_learningpath_rename_img_path_course_image_and_more.py
  api/app_sph_lms/migrations/0007_alter_learningpath_author.py
  api/app_sph_lms/models.py
  client/app/store.ts
  client/features/learning-path/learnerSlice.ts
  client/services/traineeAPI.ts
  client/src/sections/courses/LearningSection/index.tsx
  client/src/sections/learning-paths/LearnersSection/index.tsx
  client/src/shared/components/Card/CourseCard/index.tsx
  client/src/shared/components/Modal/AddLearnerModal.tsx
Labels: For Review, Approved by Mel, Approved by EJ

#124 [LMS-626] [API/INTEGRATION] Trainer can view a list of LP
  api/app_sph_lms/api/serializer/learning_path_serializer.py
  api/app_sph_lms/api/view/learning_path_view.py
  client/services/learningPathAPI.ts
  client/src/pages/trainer/courses/index.tsx
  client/src/pages/trainer/learning-paths/index.tsx
  client/src/sections/landing-page/HeroSection.tsx
  client/src/sections/learning-paths/index.tsx
  client/src/shared/components/Card/LearningPathCard/index.tsx
  client/src/shared/components/Dropdown/SortDropdown/SortDropdown.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Rene is reviewing, Approved by Mel

#126 [LMS-645] [BUGFIX] CourseCard Components & Lesson Item Component Fixes
  client/src/sections/courses/create/LessonItem.tsx
  client/src/sections/learning-paths/ContentSection/index.tsx
  client/src/sections/learning-paths/create/CourseItem.tsx
  client/src/shared/components/Card/CourseCard/index.tsx
  client/src/shared/components/Card/LearningPathCard/index.tsx
  client/src/shared/components/Card/LearningPathCourseCard/index.tsx
Labels: Approved by Franz, Approved by Mel

#129 [LMS-640] [Markup] Sign In Page
  client/src/pages/_document.tsx
  client/src/pages/auth/old/index.tsx
  client/src/pages/auth/sign-in/index.tsx
  client/src/shared/hooks/useAuthMiddleware.ts
  client/src/shared/icons/GoogleIcon.tsx
  client/src/shared/icons/SunBear.tsx
  client/tailwind.config.js
Labels: Approved by Mel, Approved by Amber

#127 [LMS-624] [API/Integration] Trainer can search learning path
  api/app_sph_lms/api/serializer/learning_path_serializer.py
  client/services/learningPathAPI.ts
  client/src/pages/trainer/learning-paths/index.tsx
  client/src/sections/learning-paths/index.tsx
Labels: For Review, Approved by Mel, Approved by Jules

#130 [LMS-650] [Markup] Trainer Dashboard
  client/src/pages/_document.tsx
  client/src/pages/trainer/dashboard/index.tsx
  client/src/shared/utils/navBarList.ts
  client/styles/globals.css
  client/tailwind.config.js
Labels: For Review, Approved by Rene, Approved by Mel

#128 [LMS-646] Learners Tab (Course & Learning Path) adjustments
  client/features/learning-path/learnerSlice.ts
  client/src/sections/courses/LearningSection/index.tsx
  client/src/sections/learning-paths/LearnersSection/index.tsx
Labels: For Review, Approved by Mel, Approved by Amber

#123 LMS-635 - [API/ Integration] [Content tab] Trainer can visit the content tab in Learning Path Detail Page
  api/app_sph_lms/admin.py
  api/app_sph_lms/api/serializer/learning_path_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/learning_path_view.py
  api/app_sph_lms/migrations/0002_alter_learningpathcourse_course_and_more.py
  api/app_sph_lms/models.py
  client/features/learning-path/learningPathSlice.ts
  client/services/learningPathAPI.ts
  client/src/pages/trainer/learning-paths/[id]/index.tsx
  client/src/sections/learning-paths/ContentSection/index.tsx
  client/src/sections/learning-paths/settingsSection/EditSettingsButton.tsx
  client/src/sections/learning-paths/settingsSection/index.tsx
Labels: Approved by Rene, Approved by Mel

#121 Deployment hotfixes v2
  client/src/features/counter/counterSlice.ts
  client/src/features/course/courseSlice.ts
  client/src/features/course/learnerSlice.ts
  client/src/features/course/lessonModalsSlice.ts
  client/src/features/learning-path/courseModalsSlice.ts
  client/src/features/learning-path/learnerSlice.ts
  client/src/features/learning-path/learningPathSlice.ts
  client/src/features/stepper/stepperSlice.ts
  client/src/features/tab/tabSlice.ts
  client/src/pages/_app.tsx
  client/src/pages/element/material/index.tsx
  client/src/pages/trainer/courses/[id]/index.tsx
  client/src/pages/trainer/courses/create/index.tsx
  client/src/pages/trainer/courses/index.tsx
  client/src/pages/trainer/learning-paths/[id]/index.tsx
  client/src/pages/trainer/learning-paths/create/index.tsx
  client/src/redux/hooks.ts
  client/src/redux/store.ts
  client/src/sections/courses/LearningSection/AddLearnerModal.tsx
  client/src/sections/courses/LearningSection/index.tsx
  client/src/sections/courses/SettingsSection/EditSettingsButton.tsx
  client/src/sections/courses/SettingsSection/index.tsx
  client/src/sections/courses/create/AddLessonSection.tsx
  client/src/sections/courses/create/InitialSection.tsx
  client/src/sections/courses/create/LessonItem.tsx
  client/src/sections/courses/create/Lessons.tsx
  client/src/sections/courses/create/PreviewSection.tsx
  client/src/sections/learning-paths/LearnersSection/index.tsx
  client/src/sections/learning-paths/create/AddCourseSection.tsx
  client/src/sections/learning-paths/create/CourseItem.tsx
  client/src/sections/learning-paths/create/CourseModal.tsx
  client/src/sections/learning-paths/create/Courses.tsx
  client/src/sections/learning-paths/create/InitialSection.tsx
  client/src/sections/learning-paths/create/PreviewSection.tsx
  client/src/sections/learning-paths/index.tsx
  client/src/sections/learning-paths/settingsSection/EditSettingsButton.tsx
  client/src/sections/learning-paths/settingsSection/index.tsx
  client/src/services/categoryAPI.ts
  client/src/services/courseAPI.ts
  client/src/services/learningPathAPI.ts
  client/src/services/traineeAPI.ts
  client/src/shared/components/Modal/AddLearnerModal.tsx
  client/src/shared/components/Stepper/index.tsx
  client/src/shared/components/Tabs/index.tsx
Labels: For Review, Approved by Mel, Approved by Amber

#134 [LMS-654] [Markup] My Trainees tab
  client/src/pages/trainee/[id]/index.tsx
  client/src/pages/trainee/index.tsx
  client/src/pages/trainer/dashboard/index.tsx
  client/src/sections/dashboard/TraineesSection.tsx
  client/src/shared/components/StudentActivity/index.tsx
  client/src/shared/components/Tabs/index.tsx
  client/src/shared/icons/FilterIcon.tsx
  client/src/shared/icons/ThreeDotsIcon.tsx
  client/tailwind.config.js
Labels: For Review, Approved by Rene, Approved by Mel

#133 [LMS-664] [MARKUP] Trainee List page
  client/src/pages/classes/[company_id]/list/index.tsx
  client/src/pages/trainer/courses/[id]/enrollUser.tsx
  client/src/pages/trainer/trainees/index.tsx
  client/src/pages/users/[company_id]/list/index.tsx
  client/src/shared/components/Table/HeaderTitle.tsx
  client/src/shared/components/Table/ListItem.tsx
  client/src/shared/components/Table/index.tsx
  client/src/shared/icons/EyeIcon.tsx
Labels: For Review, Approved by Mel, Approved by Amber

#137 [LMS-652][BE] Assign Trainers and trainees using django/python command
  api/app_sph_lms/api/view/trainee_view.py
  api/app_sph_lms/fixtures/new_erd_seeder.json
  api/app_sph_lms/management/commands/usertrainee.py
  api/app_sph_lms/management/commands/usertrainer.py
  api/app_sph_lms/migrations/0004_remove_course_company_course_trainee_and_more.py
  api/app_sph_lms/models.py
Labels: For Review, Approved by Mel, Approved by Amber

#136 [LMS 628] [API/Integration] Learning Path Detail - Sort Learners in Learners Tab
  api/app_sph_lms/api/serializer/learning_path_serializer.py
  client/src/sections/learning-paths/LearnersSection/index.tsx
  client/src/services/traineeAPI.ts
Labels: For Review, Approved by Rene, Approved by Mel

#138 [LMS-661] [MARKUP] My Learning Paths tab
  client/src/pages/trainer/dashboard/index.tsx
  client/src/sections/dashboard/LearninPathSection.tsx
  client/src/shared/components/Card/DashboardCard/index.tsx
Labels: For Review, Approved by Amber

#140 [LMS-657] [Markup] My Courses Tab
  client/src/pages/trainer/dashboard/index.tsx
  client/src/sections/dashboard/CoursesSection.tsx
  client/src/sections/dashboard/LearninPathSection.tsx
  client/src/sections/dashboard/LearningPathSection.tsx
  client/src/shared/components/Card/DashboardCard/index.tsx
Labels: For Review, Approved by Rene, Approved by Mel

#139 [LMS-665] [API/Integration] Trainee List page
  api/app_sph_lms/api/serializer/trainer_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/course_view.py
  api/app_sph_lms/api/view/trainee_view.py
  client/src/pages/trainer/trainees/index.tsx
  client/src/services/traineeAPI.ts
  client/src/shared/components/Table/ListItem.tsx
Labels: For Review, Approved by Rene, Approved by Mel

#141 [LMS-658] [API/Integration] My Course tab
  api/app_sph_lms/api/serializer/trainer_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/trainer_view.py
  client/src/features/trainer/trainerCourseSlice.ts
  client/src/redux/store.ts
  client/src/sections/dashboard/CoursesSection.tsx
  client/src/services/trainerAPI.ts
  client/src/shared/utils/interface.ts
Labels: Approved by Mel, Approved by Vali

#143 [LMS-655] [API/Integration] My Trainees tab
  api/app_sph_lms/admin.py
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/api/serializer/trainer_serializer.py
  api/app_sph_lms/api/view/course_view.py
  api/app_sph_lms/api/view/trainee_view.py
  api/app_sph_lms/migrations/0005_completedlesson.py
  api/app_sph_lms/models.py
  client/src/features/trainer/dashboard/traineeSlice.ts
  client/src/redux/store.ts
  client/src/sections/dashboard/TraineesSection.tsx
  client/src/services/traineeAPI.ts
  client/src/shared/components/Avatar/index.tsx
  client/src/shared/components/ProgressPercentage/index.tsx
  client/src/shared/components/StudentActivity/index.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Mel, Approved by Amber

#142 LMS-642 - [API/Integration] Google Authentication
  api/.env.example
  api/Pipfile
  api/Pipfile.lock
  api/app/settings.py
  api/app/urls.py
  api/app_sph_lms/api/serializer/trainer_serializer.py
  api/app_sph_lms/api/serializer/user_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/auth_view.py
  api/app_sph_lms/fixtures/user.json
  client/.env.example
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/apis/index.ts
  client/src/middlewares/AuthMiddleware.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/auth/[...nextauth].ts
  client/src/pages/auth/sign-in/index.tsx
  client/src/services/categoryAPI.ts
  client/src/services/courseAPI.ts
  client/src/services/learningPathAPI.ts
  client/src/services/traineeAPI.ts
  client/src/services/trainerAPI.ts
  client/src/shared/components/Avatar/index.tsx
  client/src/shared/components/Dropdown/NavBarDropdown/index.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/components/Spinner/index.tsx
  client/src/shared/components/StudentActivity/index.tsx
  client/src/shared/components/Tabs/index.tsx
  client/src/shared/utils/auth.ts
  client/src/shared/utils/helpers.ts
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Rene, Approved by Mel

#144 [LMS-662] [API/Integration] My Learning Paths tab
  api/app_sph_lms/api/serializer/trainer_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/trainer_view.py
  client/src/features/trainer/trainerLearningPathSlice.ts
  client/src/pages/trainer/learning-paths/create/index.tsx
  client/src/redux/store.ts
  client/src/sections/dashboard/LearningPathSection.tsx
  client/src/services/trainerAPI.ts
  client/src/shared/components/Tabs/index.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Mel, Approved by Amber

#145 [LMS-676] [BUGFIX] Markup adjustments
  client/src/pages/trainer/courses/index.tsx
  client/src/pages/trainer/dashboard/index.tsx
  client/src/pages/trainer/learning-paths/index.tsx
  client/src/sections/learning-paths/create/InitialSection.tsx
  client/src/shared/components/Dropdown/SortDropdown/SortDropdown.tsx
  client/src/shared/components/Dropdown/index.tsx
  client/src/shared/components/Tabs/index.tsx
Labels: For Review, Approved by Mel, Approved by Amber

#146 LMS-685 - CSRF error
  api/app/settings.py
  client/src/services/categoryAPI.ts
  client/src/services/courseAPI.ts
  client/src/services/learningPathAPI.ts
  client/src/services/traineeAPI.ts
  client/src/services/trainerAPI.ts
  client/src/shared/utils/helpers.ts
Labels: For Review, Approved by Rene, Approved by Mel

#147 [LMS-680][MARKUP] Trainee Dashboard
  api/Dockerfile
  client/src/pages/trainee/dashboard/index.tsx
  client/src/pages/trainer/dashboard/index.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Mel, Approved by Vali

#148 [LMS-678] Update Models in reference to updated ERD
  api/.env.example
  api/Pipfile
  api/app/settings.py
  api/app_sph_lms/admin.py
  api/app_sph_lms/api/serializer/class_serializer.py
  api/app_sph_lms/api/serializer/company_serializer.py
  api/app_sph_lms/api/serializer/trainee_serializer.py
  api/app_sph_lms/api/serializer/trainer_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/class_view.py
  api/app_sph_lms/api/view/learning_path_view.py
  api/app_sph_lms/api/view/trainer_view.py
  api/app_sph_lms/api/view/user_view.py
  api/app_sph_lms/fixtures/new_erd_seeder.json
  api/app_sph_lms/fixtures/social_app_seeder.json
  api/app_sph_lms/management/commands/seed_social_apps.py
  api/app_sph_lms/migrations/0001_initial.py
  api/app_sph_lms/migrations/0002_alter_learningpathcourse_course_and_more.py
  api/app_sph_lms/migrations/0003_rename_img_path_user_image_remove_user_role_and_more.py
  api/app_sph_lms/migrations/0004_remove_course_company_course_trainee_and_more.py
  api/app_sph_lms/migrations/0005_completedlesson.py
  api/app_sph_lms/models.py
Labels: For Review, Approved by Mel, Approved by Amber

#152 [LMS-681] [MARKUP] [Trainee] My Course Tab
  client/src/pages/trainee/dashboard/index.tsx
  client/src/sections/dashboard/trainee/CoursesSection.tsx
  client/src/shared/components/Card/TraineeCourseCard/index.tsx
  client/src/shared/icons/ChevronRightIcon.tsx
Labels: For Review, Approved by Elyric, Approved by Amber

#155 LMS-686 - Restrict users from visiting unauthorized pages on FE and update navbar based on the user role
  client/src/middleware.ts
  client/src/pages/trainee/dashboard/index.tsx
  client/src/pages/trainer/dashboard/index.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/utils/helpers.ts
  client/src/shared/utils/interface.ts
  client/src/types/next-auth.d.ts
Labels: For Review, Approved by Rene, Approved by Mel

#154 [LMS-682][MARKUP] My Learning Paths Tab
  client/src/pages/trainee/dashboard/index.tsx
  client/src/sections/trainee/MyLearningPathSection/index.tsx
  client/src/shared/components/Card/LearningPathCard/index.tsx
  client/src/shared/components/Tabs/index.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Rene, Approved by Mel

#156 LMS-687 [Course & Learning Path] Updating on settings tab dont change…
  client/src/services/courseAPI.ts
Labels: For Review, Approved by Mel, Approved by Jules

#150 [LMS-677] [BUGFIX] [Course & Learning Path Detail Page] Return 404 on non-existing ID
  client/src/pages/404.tsx
  client/src/pages/500.tsx
  client/src/pages/trainer/courses/[id]/index.tsx
  client/src/pages/trainer/learning-paths/[id]/index.tsx
  client/src/shared/components/Card/TraineeCourseCard/index.tsx
  client/src/shared/layouts/Error/index.tsx
Labels: For Review, Approved by Mel, Approved by Amber

#157 [LMS-674][Course][Content Tab] Content Width and Lesson Link
  client/src/sections/courses/ContentSection.tsx
  client/src/shared/components/Iframe/index.tsx
  client/src/shared/components/SidebarContent/index.tsx
  client/src/shared/utils/helpers.ts
Labels: For Review, Approved by Mel, Approved by Jules

#151 LMS-683 - [API / INTEGRATION] My Course Tab
  api/app_sph_lms/api/serializer/course_serializer.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/view/course_view.py
  client/src/sections/dashboard/trainee/CoursesSection.tsx
  client/src/services/traineeAPI.ts
  client/src/shared/components/Card/TraineeCourseCard/index.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Mel, Approved by Vali

#153 [LMS-684] [API/Integration] My Learning Paths Tab
  api/app_sph_lms/api/view/learning_path_view.py
  client/src/pages/trainee/dashboard/index.tsx
  client/src/sections/dashboard/trainee/MyLearningPathSection.tsx
  client/src/sections/trainee/MyLearningPathSection/index.tsx
  client/src/services/learningPathAPI.ts
Labels: For Review, Approved by Franz, Approved by Mel

#135 [LMS 636] - [API/ Integration] Settings tab in learning path detail page
  api/app_sph_lms/api/serializer/learning_path_serializer.py
  api/app_sph_lms/api/view/learning_path_view.py
  client/src/features/learning-path/learningPathSlice.ts
  client/src/sections/learning-paths/settingsSection/EditSettingsButton.tsx
  client/src/sections/learning-paths/settingsSection/index.tsx
  client/src/services/learningPathAPI.ts
Labels: Approved by Franz, Approved by Mel
