Repository framgia/sph-lms, pull requests merged in 2023-03, with the labels that each got.

#12 Setup Linter
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/hello.ts
  client/src/pages/index.tsx
Labels: Approved by Joshua

#6 [feature] Iframe
  client/.eslintrc.json
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Iframe/index.tsx
Labels: For Review, Approved by Marielle, Approved by Joshua

#3 [LAYOUTS] Layout-Container
  client/src/pages/demo/layouts/container.tsx
  client/src/shared/layouts/container/index.tsx
  client/styles/globals.css
Labels: For Review, Approved by Joshua

#5 [LAYOUTS] Layout-learning
  client/src/pages/demo/layouts/learning.tsx
  client/src/shared/icons/menu.tsx
  client/src/shared/icons/next.tsx
  client/src/shared/icons/previous.tsx
  client/src/shared/layouts/layout-learning.tsx
  client/src/shared/layouts/sidebar.tsx
Labels: enhancement, Approved by Joshua

#7 [CONTENTS] Cards
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Card/index.tsx
  client/styles/globals.css
Labels: Approved by Marielle

#8 [Reusable Component] Breadcrumbs
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Breadcrumbs/index.tsx
Labels: Approved by Marielle

#18 [Reusable Component] Pagination
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Pagination/index.tsx
Labels: For Review, Approved by Marielle, Approved by Kurt

#11 [FORM] Text Field
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/TextField/index.tsx
Labels: Approved by Marielle, Approved by Joshua

#16 [Reusable Component] Sidebar
  client/src/pages/demo/layouts/sidebar.tsx
  client/src/shared/layouts/SideBar/SideBar.tsx
  client/styles/globals.css
Labels: For Review, Approved by Marielle, Approved by Rene

#10 [BUTTON] Dropdown
  client/src/pages/demo/components/index.tsx
  client/src/pages/demo/layouts/Container.tsx
  client/src/pages/demo/layouts/Learning.tsx
  client/src/shared/components/Breadcrumbs/index.tsx
  client/src/shared/components/Card/index.tsx
  client/src/shared/components/Dropdown/index.tsx
  client/src/shared/components/Iframe/index.tsx
  client/src/shared/components/Pagination/index.tsx
  client/src/shared/icons/ChevronDownIcon.tsx
  client/src/shared/icons/MenuIcon.tsx
  client/src/shared/icons/NextIcon.tsx
  client/src/shared/icons/PreviousIcon.tsx
  client/src/shared/layouts/LayoutLearning.tsx
  client/src/shared/layouts/Sidebar.tsx
Labels: For Review, Approved by Marielle, Approved by Kurt

#19 [NAVIGATION] Tabs
  client/src/pages/demo/layouts/tabs.tsx
  client/src/shared/layouts/tabs.tsx
Labels: For Review, Approved by Marielle, Approved by Rene

#13 Features/input field
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/InputField/index.tsx
Labels: For Review, Approved by Marielle, Kurt is reviewing

#22 [Reusable Component] Searchbar
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
Labels: For Review, Approved by Marielle, Approved by Miko

#14 [CONTENTS] Collapse
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Collapse/Collapse.tsx
Labels: For Review, Approved by Marielle, Rene is reviewing, Miko is reviewing

#17 [Reusable Component] Layout-Right-Sidebar
  client/src/pages/demo/layouts/SidebarLayout.tsx
  client/src/shared/layouts/Right Side Bar/LeftSideContainer.tsx
  client/src/shared/layouts/Right Side Bar/RightSideBar.tsx
Labels: For Review, Approved by Marielle, Rene is reviewing

#26 [Bugfix] Fix Issues For Docker Build
  client/src/pages/demo/components/index.tsx
  client/src/pages/demo/layouts/Learning.tsx
  client/src/pages/demo/layouts/SidebarLayout.tsx
  client/src/pages/demo/layouts/sidebar.tsx
  client/src/shared/components/Card/index.tsx
  client/src/shared/icons/NextIcon.tsx
  client/src/shared/icons/PreviousIcon.tsx
  client/src/shared/layouts/Container/index.tsx
  client/src/shared/layouts/LayoutLearning/LayoutLearning.tsx
  client/src/shared/layouts/LayoutLearning/Sidebar.tsx
  client/src/shared/layouts/RightSideBar/LeftSideContainer.tsx
  client/src/shared/layouts/RightSideBar/RightSideBar.tsx
  client/src/shared/layouts/SideBar/index.tsx
Labels: For Review, Approved by Marielle, Approved by Kurt

#15 [Reusable Component] Event Button
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Button/index.tsx
Labels: For Review, Approved by Marielle, Approved by Miko

#23 [BE] Course Migration and Seeder
  .vscode/settings.json
  api/app/settings.py
  api/app/urls.py
  api/app_sph_lms/__init__.py
  api/app_sph_lms/admin.py
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/views.py
  api/app_sph_lms/apps.py
  api/app_sph_lms/fixtures/seeder.json
  api/app_sph_lms/migrations/0001_initial.py
  api/app_sph_lms/migrations/0002_auto_20230308_1542.py
  api/app_sph_lms/migrations/0003_auto_20230308_1551.py
  api/app_sph_lms/migrations/__init__.py
  api/app_sph_lms/models.py
  api/app_sph_lms/tests.py
Labels: For Review, Approved by Marielle, Approved by Miko

#27 [BUTTON] Radiobutton
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Radiobutton/index.tsx
Labels: For Review, Approved by Marielle, Approved by Rene

#29 [BUG FIX] Fixed dropdown Issue
  client/src/shared/components/Dropdown/index.tsx
Labels: For Review, Approved by Marielle, Approved by Kurt, Approved by Rene

#28 [NAVIGATION] Navbar
  client/src/pages/demo/layouts/navbar.tsx
  client/src/shared/components/Avatar/index.tsx
  client/src/shared/components/NavLink/index.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/icons/SettingsIcon.tsx
Labels: For Review, Approved by Marielle, Approved by Rene

#20 [Reusable Component] Table
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Table/index.tsx
Labels: For Review, Approved by Marielle, Approved by Kurt

#21 [Setup] Dockerize apps
  README.md
  api/.env.example
  api/.gitignore
  api/Dockerfile
  api/Pipfile
  api/Pipfile.lock
  api/app/asgi.py
  api/app/settings.py
  api/app/urls.py
  api/app/wsgi.py
  api/manage.py
  api/my.cnf
  api/venv_requirements.txt
  api/wait.sh
  client/Dockerfile
  client/next.config.js
  docker-compose.yml
Labels: For Review, Marielle is reviewing, Approved by Rene, Approved by Miko

#30 [LMS-326][Reusable Component] Table-v2
  client/src/pages/demo/components/index.tsx
  client/src/pages/demo/layouts/navbar.tsx
  client/src/shared/components/Checkbox/index.tsx
  client/src/shared/components/NavLink/index.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/components/Radiobutton/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/components/Select/index.tsx
  client/src/shared/components/Table/index.tsx
Labels: For Review, Approved by Marielle, Approved by Joshua

#32 [LMS-331][Bug Fix] Fixed Dropdown Issue
  client/src/shared/components/Dropdown/index.tsx
  client/src/shared/hooks/useOutsideClick.tsx
Labels: For Review, Approved by Marielle, Approved by Joshua

#36 [LMS-311] [NAVIGATION] Navbar
  client/src/shared/components/Avatar/index.tsx
  client/src/shared/components/NavLink/index.tsx
  client/src/shared/icons/SettingsIcon.tsx
Labels: For Review, Approved by Marielle, Approved by Joshua

#31 [LMS-322][BUTTON] Radio Button
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/RadioButton/index.tsx
Labels: enhancement, For Review, Approved by Marielle, Approved by Joshua

#37 [LMS-77][FE] Create course page
  client/src/pages/courses/create.tsx
  client/src/shared/components/Button/index.tsx
  client/src/shared/components/Footer/index.tsx
Labels: For Review, Approved by Marielle

#39 [LMS-328][FE] View as Function
  client/public/image1.jpg
  client/src/pages/trainer/courses/list/index.tsx
  client/src/sections/courses/list/right-side-container.tsx
  client/src/sections/courses/list/view-as.tsx
  client/src/shared/cards/GridCard.tsx
  client/src/shared/cards/ListCard.tsx
  client/src/shared/components/Dropdown/index.tsx
  client/src/shared/icons/GridIcon.tsx
  client/src/shared/icons/ListIcon.tsx
  client/src/shared/layouts/RightSideBar/LeftSideContainer.tsx
  client/src/shared/layouts/RightSideBar/RightSideBar.tsx
  client/tailwind.config.js
Labels: For Review, Approved by Marielle, Approved by Joshua, Kurt is reviewing, Approved by Miko

#40 [LMS-79][Integration] Implement Course Create
  README.md
  api/Pipfile
  api/Pipfile.lock
  api/app/settings.py
  client/.env.example
  client/package-lock.json
  client/package.json
  client/src/apis/index.ts
  client/src/pages/_app.tsx
  client/src/pages/courses/create.tsx
  client/src/pages/demo/components/index.tsx
  client/src/pages/demo/layouts/navbar.tsx
  client/src/pages/trainer/course/create.tsx
  client/src/pages/trainer/course/detail/[id].tsx
  client/src/shared/components/Breadcrumbs/index.tsx
  client/src/shared/components/InputField/index.tsx
  client/src/shared/components/Select/index.tsx
  client/src/shared/components/TextField/index.tsx
  client/src/shared/hooks/useCreateCourse.ts
  client/src/shared/utils/index.ts
Labels: For Review, Approved by Marielle, Kurt is reviewing, Approved by Miko

#44 [BUGFIX] Fix TextField Props & RadioButton import
  client/.env.example
  client/src/apis/index.ts
  client/src/pages/demo/components/index.tsx
  client/src/sections/courses/list/right-side-container.tsx
Labels: For Review, Approved by Marielle, Approved by Kurt

#46 [LMS-83][FE][REUSABLE]Table List
  .vscode/settings.json
  client/src/pages/demo/components/data.json
  client/src/pages/demo/components/index.tsx
  client/src/shared/components/Table/index.tsx
  client/tailwind.config.js
Labels: For Review, Approved by Marielle, Approved by Rene

#45 [LMS-333][Integration] Show Per Page
  api/app_sph_lms/api/urls.py
  client/package-lock.json
  client/package.json
  client/src/pages/trainer/course/[id]/enrollUser.tsx
  client/src/shared/components/Breadcrumbs/index.tsx
  client/src/shared/components/Select/index.tsx
  client/src/shared/components/Table/index.tsx
  client/src/shared/hooks/useShowPerPage.ts
  client/src/shared/utils/axios.ts
  client/src/shared/utils/index.ts
  client/src/shared/utils/interface.ts
  client/src/shared/utils/toastify.ts
Labels: For Review, Approved by Marielle

#42 [LMS-74][INTEGRATION] Search function
  .gitignore
  api/Pipfile
  api/app_sph_lms/api/serializers.py
  client/.gitignore
  client/src/pages/trainer/courses/list/index.tsx
  client/src/sections/courses/list/view-as.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/hooks/useSearchCourse.ts
  client/src/shared/utils/date.ts
  client/src/shared/utils/debounce.ts
  client/src/shared/utils/index.ts
Labels: For Review, Approved by Marielle, Approved by Rene

#50 [LMS-335][FE]Course Detail Header
  client/src/pages/trainer/course/detail/[id].tsx
  client/src/shared/icons/EllipsesHorizontalIcon.tsx
Labels: For Review, Approved by Marielle, Rene is reviewing

#49 [LMS-84][Frontend] Selection Modal
  client/package-lock.json
  client/package.json
  client/src/pages/demo/components/data.json
  client/src/pages/demo/layouts/LearnersTab.tsx
  client/src/shared/components/SelectionModal/index.tsx
  client/src/shared/icons/TrashIcon.tsx
Labels: For Review, Approved by Marielle, Approved by Rene

#47 [LMS-82][Frontend] Course Settings
  client/package-lock.json
  client/package.json
  client/src/pages/trainer/course/detail/[id].tsx
  client/src/shared/components/Button/index.tsx
  client/src/shared/components/RadioButton/index.tsx
  client/src/shared/components/RichInputTextField/index.tsx
  client/src/shared/components/ShareableLink/index.tsx
  client/src/shared/layouts/CourseSettingTab/index.tsx
  client/src/shared/layouts/CourseSettingsSideBar/index.tsx
  client/src/shared/layouts/RightSideBar/LeftSideContainer.tsx
  client/src/shared/layouts/RightSideBar/RightSideBar.tsx
Labels: For Review, Approved by Marielle, Approved by Rene

#41 [LMS-329][Backend] Filter, Sort, and Search API
  .gitignore
  api/Pipfile
  api/app/settings.py
  api/app_sph_lms/api/views.py
  api/app_sph_lms/migrations/0004_alter_course_id_alter_coursecategory_id.py
  api/app_sph_lms/migrations/0005_course_is_active.py
  api/app_sph_lms/models.py
  client/src/pages/demo/components/index.tsx
  client/src/pages/trainer/courses/list/index.tsx
  client/src/sections/courses/list/right-side-container.tsx
  client/src/sections/courses/list/view-as.tsx
  client/src/shared/components/Card/index.tsx
  client/src/shared/components/Checkbox/index.tsx
  client/src/shared/components/RadioButton/index.tsx
  client/src/shared/components/SearchBar/SearchBar.tsx
  client/src/shared/hooks/useFilterCourse.tsx
  client/src/shared/hooks/useSearchCourse.ts
  client/src/shared/layouts/CourseSettingTab/index.tsx
  client/src/shared/layouts/RightSideBar/RightSideBar.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Marielle, Approved by Kurt

#43 [LMS-337][DOCKER] Fix client docker issues
  client/.dockerignore
  client/Dockerfile
  docker-compose.yml
Labels: Approved by Marielle, Approved by Rene

#33 [LMS-75][Integration] Sort By function
  api/app_sph_lms/api/views.py
  client/src/pages/trainer/courses/list/index.tsx
  client/src/sections/courses/list/view-as.tsx
  client/src/shared/hooks/useFilterCourse.tsx
  client/src/shared/hooks/useSortByCourse.ts
  client/src/shared/layouts/RightSideBar/RightSideBar.tsx
Labels: For Review, Approved by Marielle, Approved by Rene

#51 [LMS-346][BE] Sign In API
  api/Pipfile
  api/Pipfile.lock
  api/app/settings.py
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/views.py
Labels: For Review, Approved by Marielle, Approved by Miko

#52 [LMS-340][FE][Markup] Home Page
  client/src/pages/home/index.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/utils/navBarList.ts
Labels: For Review, Approved by Marielle, Approved by Kurt

#54 [LMS-344][FE][Markup] Sign-in Page
  client/src/pages/auth/sign-in/index.tsx
  client/src/pages/home/index.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/utils/auth.ts
  client/src/shared/utils/index.ts
Labels: For Review, Approved by Marielle, Approved by Kurt

#56 [LMS-338] Landing Page
  client/public/communication.png
  client/public/completed.png
  client/public/experience.png
  client/public/hero_image.jpg
  client/public/improve_management.png
  client/public/logo.png
  client/public/next.svg
  client/public/notfoundpic.jpg
  client/public/notfoundpic.png
  client/public/profile_icon.png
  client/public/save-time.png
  client/public/stakeholder.png
  client/public/thirteen.svg
  client/public/vercel.svg
  client/src/pages/404.tsx
  client/src/pages/index.tsx
  client/src/sections/landingPage/benefits.tsx
  client/src/sections/landingPage/hero.tsx
  client/src/sections/landingPage/navbar.tsx
  client/src/sections/landingPage/testimonials.tsx
Labels: For Review, Approved by Marielle, Approved by Kurt

#55 [LMS-343][BE][Migration & Seeders] Sign In Page
  api/app/settings.py
  api/app_sph_lms/admin.py
  api/app_sph_lms/fixtures/seeder.json
  api/app_sph_lms/migrations/0001_initial.py
  api/app_sph_lms/migrations/0002_auto_20230308_1542.py
  api/app_sph_lms/migrations/0003_auto_20230308_1551.py
  api/app_sph_lms/migrations/0004_alter_course_id_alter_coursecategory_id.py
  api/app_sph_lms/migrations/0005_course_is_active.py
  api/app_sph_lms/models.py
Labels: For Review, Approved by Marielle, Approved by Kurt, Approved by Miko

#59 [LMS-338] Landing Page V2
  client/src/pages/index.tsx
  client/src/sections/landing-page/BenefitSection.tsx
  client/src/sections/landing-page/HeroSection.tsx
  client/src/sections/landing-page/NavbarSection.tsx
  client/src/sections/landing-page/TestimonialSection.tsx
Labels: For Review, Approved by Marielle

#58 [LMS-347][Integration] Sign In page
  api/app/settings.py
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/views.py
  client/src/apis/index.ts
  client/src/pages/_app.tsx
  client/src/pages/auth/sign-in/index.tsx
  client/src/pages/home/index.tsx
  client/src/pages/trainer/courses/list/index.tsx
  client/src/shared/components/Avatar/index.tsx
  client/src/shared/components/Dropdown/index.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/hooks/useAuthMiddleware.ts
  client/src/shared/hooks/useAuthSignIn.ts
  client/src/shared/hooks/useCreateCourse.ts
  client/src/shared/hooks/useFilterCourse.tsx
  client/src/shared/hooks/useSearchCourse.ts
  client/src/shared/hooks/useShowPerPage.ts
  client/src/shared/hooks/useSortByCourse.ts
  client/src/shared/utils/auth.ts
Labels: For Review, Approved by Marielle, Approved by Kurt

#53 [LMS-341][BE/API] Sign Out
  api/app/urls.py
  api/app_sph_lms/api/serializers.py
  api/app_sph_lms/api/urls.py
  api/app_sph_lms/api/views.py
  api/app_sph_lms/fixtures/seeder.json
  api/app_sph_lms/forms.py
  api/app_sph_lms/migrations/0001_initial.py
  api/app_sph_lms/models.py
Labels: For Review, Approved by Marielle, Approved by Rene, Miko is reviewing

#62 [LMS-357][BUG FIX] Fix markup sign-in page
  client/src/shared/components/Avatar/index.tsx
  client/src/shared/components/Navbar/index.tsx
Labels: For Review, Approved by Marielle, Approved by Rene

#57 [LMS-342][Integration] Sign out
  client/src/shared/components/Dropdown/index.tsx
  client/src/shared/components/Navbar/index.tsx
  client/src/shared/hooks/useAuthMiddleware.ts
  client/src/shared/hooks/useAuthSignIn.ts
  client/src/shared/hooks/useSignOut.ts
  client/src/shared/utils/navBarList.ts
Labels: For Review, Approved by Marielle, Rene is reviewing

#61 [LMS-354][FE][Markup][Reusable] Add Modal & Edit Modal
  client/src/pages/demo/components/index.tsx
  client/src/pages/users/[company_id]/list/index.tsx
  client/src/shared/components/Button/index.tsx
  client/src/shared/components/InputField/index.tsx
  client/src/shared/components/Modal/Modal.tsx
  client/src/shared/hooks/useEditAddUser.ts
  client/src/shared/icons/EditIcon.tsx
  client/src/shared/icons/XmarkIcon.tsx
Labels: For Review, Approved by Marielle, Approved by Rene, Approved by Miko

#60 [LMS-350][FE][Markup]User List Page
  client/src/pages/users/[company_id]/list/index.tsx
  client/src/shared/components/Pagination/index.tsx
  client/src/shared/components/Table/index.tsx
  client/src/shared/icons/EditIcon.tsx
  client/src/shared/utils/interface.ts
Labels: For Review, Approved by Marielle, Approved by Franz
